print("hello world")
for i in range(5):
    print(i)
print("Loop finished")
print("Goodbye!")  
while False:
    print("This will never print")  
print("This is the end of the script.")
print("This is a simple Python script.") 
print("This script demonstrates basic print statements and loops.")
print("Starting the loop:")
for i in range(3):
    print(f"Iteration {i}")
print("Loop ended.")
print("Exiting the script now.")
print("This is the final line of the script.")
print("This is the first line of the script.")
print("This script is running.")
print("This is a test script.")
print("This script prints numbers from 0 to 4:")
for i in range(5):
    print(i)
print("Script execution completed.")
print("This is a sample Python script.")
print("This script will print numbers from 0 to 4:")
for i in range(5):
    print(i)
print("End of the script.")
print("This is a simple Python script.")
print("This script demonstrates basic print statements and loops.")
print("Starting the loop:")
for i in range(3):
    print(f"Iteration {i}")
print("Loop ended.")
print("Exiting the script now.")
print("This is the final line of the script.")
print("This is the first line of the script.")
print("This script is running.")
print("This is a test script.")
print("This script prints numbers from 0 to 4:")
for i in range(5):
    print(i)
print("Script execution completed.")
print("This is a sample Python script.")
print("This script will print numbers from 0 to 4:")
for i in range(5):
    print(i)
print("End of the script.")
print("This is a simple Python script.")
print("This script demonstrates basic print statements and loops.")
print("Starting the loop:")
for i in range(3):
    print(f"Iteration {i}")
print("Loop ended.")
print("Exiting the script now.")
print("This is the final line of the script.")
print("This is the first line of the script.")
print("This script is running.")
print("This is a test script.")
print("This script prints numbers from 0 to 4:")
for i in range(5):
    print(i)
print("Script execution completed.")
print("This is a sample Python script.")
print("This script will print numbers from 0 to 4:")
for i in range(5):
    print(i)
print("End of the script.")
print("This is a simple Python script.")
print("This script demonstrates basic print statements and loops.")
print("Starting the loop:")
for i in range(3):
    print(f"Iteration {i}")
print("Loop ended.")
print("Exiting the script now.")
print("This is the final line of the script.")
print("This is the first line of the script.")
print("This script is running.")
print("This is a test script.")
print("This script prints numbers from 0 to 4:")
for i in range(5):
    print(i)
print("Script execution completed.")
print("This is a sample Python script.")
print("This script will print numbers from 0 to 4:")
for i in range(5):
    print(i)
print("End of the script.")
print("This is a simple Python script.")
print("This script demonstrates basic print statements and loops.")
print("Starting the loop:")
for i in range(3):
    print(f"Iteration {i}")
print("Loop ended.")
print("Exiting the script now.")
print("This is the final line of the script.")
print("This is the first line of the script.")
print("This script is running.")
print("This is a test script.")
print("This script prints numbers from 0 to 4:")